In [4]:
import pandas as pd
import numpy as np
q=pd.read_csv('sf_restaurant_health_violations.csv',encoding='latin-1')

,usiness_id,business_name,business_address,business_city,business_state,business_postal_code,business_latitude,business_longitude,business_location,business_phone_number,inspection_id,inspection_date,inspection_score,inspection_type,violation_id,violation_description,risk_category
0,5800,John Chin Elementary School,350 Broadway St,San Francisco,CA,94133.0,37.798,-122.403,"{'longitude': '-122.403154', 'needs_recoding':...",NaN,5800_20171017,10/17/2017,98.0,Routine - Unscheduled,5800_20171017_103149,Wiping cloths not clean or properly stored or ...,Low Risk
1,64236,Sutter Pub and Restaurant,700 Sutter St,San Francisco,CA,94102.0,37.789,-122.412,"{'longitude': '-122.41188', 'needs_recoding': ...",NaN,64236_20170725,7/25/2017,88.0,Routine - Unscheduled,64236_20170725_103133,Foods not protected from contamination,Moderate Risk
2,1991,SRI THAI CUISINE,4621 LINCOLN Way,San Francisco,CA,94122.0,37.764,-122.508,"{'longitude': '-122.507779', 'needs_recoding':...",NaN,1991_20171129,11/29/2017,86.0,Routine - Unscheduled,1991_20171129_103139,Improper food storage,Low Risk
3,3816,Washington Bakery & Restaurant,733 Washington St,San Francisco,CA,94108.0,37.795,-122.406,"{'longitude': '-122.405845', 'needs_recoding':...",NaN,3816_20160728,7/28/2016,67.0,Routine - Unscheduled,3816_20160728_103108,Contaminated or adulterated food,High Risk
4,39119,Brothers Restaurant,4128 GEARY Blvd,San Francisco,CA,94118.0,37.781,-122.464,"{'longitude': '-122.463762', 'needs_recoding':...",NaN,39119_20160718,7/18/2016,79.0,Routine - Unscheduled,39119_20160718_103133,Foods not protected from contamination,Moderate Risk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292,500,Roxanne Cafe,570 Powell St,San Francisco,CA,94108.0,37.790,-122.409,"{'longitude': '-122.408688', 'needs_recoding':...",NaN,500_20150930,9/30/2015,86.0,Routine - Unscheduled,500_20150930_103154,Unclean or degraded floors walls or ceilings,Low Risk
293,500,Roxanne Cafe,570 Powell St,San Francisco,CA,94108.0,37.790,-122.409,"{'longitude': '-122.408688', 'needs_recoding':...",NaN,500_20150930,9/30/2015,86.0,Routine - Unscheduled,500_20150930_103119,Inadequate and inaccessible handwashing facili...,Moderate Risk
294,500,Roxanne Cafe,570 Powell St,San Francisco,CA,94108.0,37.790,-122.409,"{'longitude': '-122.408688', 'needs_recoding':...",NaN,500_20180403,4/3/2018,92.0,Routine - Unscheduled,500_20180403_103120,Moderate risk food holding temperature,Moderate Risk
295,500,Roxanne Cafe,570 Powell St,San Francisco,CA,94108.0,37.790,-122.409,"{'longitude': '-122.408688', 'needs_recoding':...",NaN,500_20180403,4/3/2018,92.0,Routine - Unscheduled,500_20180403_103144,Unapproved or unmaintained equipment or utensils,Low Risk
296,500,Roxanne Cafe,570 Powell St,San Francisco,CA,94108.0,37.790,-122.409,"{'longitude': '-122.408688', 'needs_recoding':...",NaN,500_20161128,11/28/2016,89.0,Routine - Unscheduled,500_20161128_103105,Improper cooling methods,High Risk

Determine the change in the number of daily violations by calculating the difference between the count of current and previous violations by inspection date.
Output the inspection date and the change in the number of daily violations. Order your results by the earliest inspection date first.

In [14]:
# change the type of inspection_date column into datetime
q.inspection_date=q.inspection_date.apply(pd.to_datetime)
# Find the total violations of each inspection date, rename column & sort by the earliest inspection date
q=q.groupby('inspection_date')['violation_id'].count().reset_index().rename(columns={'violation_id':'total_violations'}).sort_values('inspection_date',ascending=False)

    inspection_date  total_violations
226      2018-08-28                 1
225      2018-08-02                 1
224      2018-07-25                 0
223      2018-07-24                 1
222      2018-07-20                 0
..              ...               ...
4        2015-09-28                 1
3        2015-09-23                 0
2        2015-09-18                 0
1        2015-09-15                 0
0        2015-09-08                 1

[227 rows x 2 columns]

In [19]:
# find the previous violations of each inspection date, fill na with 0
q['previous_violations']=q.total_violations.shift(1).fillna(0)

In [22]:
# add the violation diff
q['violation_diff']=q.total_violations-q.previous_violations
q